
vocab_list = {
    "Diminish" : "less",
    "Encompass" : "hold, cover",
    "Concede": "admits",
    "Declarative clause": " 陈述性从句",
    "interrogative clause": "疑问从句",
    "tenuous": "脆弱的",
    "contentious": "有争议的",
    "conspicuous": "outstanding, 显眼的",
    "repudiation": "decline, 反对",
    "intricate" : "complex, 错综复杂的",
    "ornamentation ":"装饰",
    "reminiscent": "令人怀念的",
    "manuscript":"手稿",
    "meticulously":"精心设计的",
    "redress":"矫正",
    "cohort":"队列",
    "Exacerbate":"加剧",
    "Epitomize":"缩影，概括",
    "Preclude":"排除",
    "Dispute":"争论",
    "Multitude":"民众",
    "Festive":"喜庆的",
    "Asserting possession of":"主张拥有",
    "Impede":"受阻",
    "Zenith":"顶点,极盛",
    "Espousing":"拥护",
    "Outspoken":"直言不讳的",
    "low-profile":"低调的",
    "averse":"厌恶",
    "Antropogenic":"人为的",
    "Permeate":"渗透",
    "Impervious":"不透水的",
    "Aquifer":"含水层",
    "Captive":"俘虏",
    "Inadvertently":"不经意间",
    "Cognitive":"认知的",
    "Carcasses":"尸体",
    "Gnawing":"啃咬",
    "Cuisine":"美食",
    "Epitomize":"缩影",
    "Keenly":"敏锐的",
    "Finite":"有限的",
    "In hindsight, ...":"事后诸葛亮",
    "Moreover":"而且",
    "Paradigm":"Example, 范例",
    "decisive":"决定性",
    "dormant":"休眠的",
    "confined to":"受限于",
    "repressed by ...":"受...压制",
    "prevalent":"流行的",
    "concede":"承认",
    "a criticism leveled against":"对...的批评",
    "grand":"盛大的",
    "Edifice":"建筑物",
    "trustee":"受托人",
    "contemporary":"当代的",
    "depict":"描绘",
    "an apt assesment":"恰当的评价",
    "disparity":"差异",
    "archaeologist":"考古学家",
    "fragments":"碎片",
    "colon":":",
    "germination":"发芽",
    "quota":"配额",
    "perceive":"感知，察觉",
    "conform to":"符合",
    "carefree":"畅快的",
    "jingle":"叮当响",
    "reimagines":"re-imagines",
    "prominently":"突出的",
    "engulf":"吞没",
    "comprise":"包括",
    "provoke":"挑衅, 惹",
    "csomplementary":"补充",
    "disparate":"不同的",
    "interchangeable":"可互换的",
    "descend":"下降, 繁衍",
    "contamnated":"被污染的",
    "shoots":"芽",
    "by no means":"绝不是",
    "Mesopotamian":"美索不达米亚",
    "tenuous":"脆弱的",
    "nuanced":"细致入微的",
    "obtrusive":"突兀的",
    "concealed":"暗的, 隐蔽的",
    "peripheral":"周边的, 肤浅的",
    "prudent":"谨慎的",
    "overt":"公开的",
    "cordial":"亲切的",
    "advert":"v. 注意到",
    "deliberately":"故意的，有意的",
    "sanction":"制裁",
    "ameliorate":"改善",
    "rationalize":"v. 合理化",
    "postulate":"v. 假定 / 要求",
    "antagonistic":"敌对的",
    "imitate":"模仿",
    "inconsequential":"无关紧要的",
    "undermine":"破坏, 削弱",
    "be obliged to do sth":"有义务做...",
    "sb proving false to the contract":"sb 违反合同",
    "upon a pinch":"在紧要关头",
    "to have envinced":"以表明",
    "thwart in ..":"在... 中受阻",
    "be susceptible":"易受... 影响",
    "a singular patience and mildness":"非凡的耐心和温和",
    "be taken advantage of":"被利用",
    "attribute A to B":"将 A 归因于 B",
    "ambivalence":"矛盾心理",
    "merit":"优点",
    "discriminate":"区别, 鉴别",
    "discriminate against":"歧视...",
    "derivative":"衍生物, 导数",
    "unintelligible":"难以理解的",
    "contempt":"鄙视",
    "genuie":"真的, 真诚的",
    "disdain":"蔑视",
    "crutacean":"甲克类动物",
    "disclosure":"n. 泄露, 披露",
    "adversary":"n. 对手, 敌手",
    "confidential":"机密的",
    "toutine":"n. 常规, 例行",
    "contrive":"图谋, 做作的, 瞎造",
    "deceptive":"欺骗性的",
    "stimuli":"刺激",
    "innocuous":"无害的",
    "benign":"良性的",
    "the reign of a monarch":"在君主的统治之下",
    "legitimacy":"合法性",
    "corollary ":"推论的",
    "disengage":"脱离",
    "buttress":"支持",
    "reciprocate":"往复, 往返, 往来, 报答",
    "tranquilly":"平静的",
    "ever":"frequently, at any time, ",
    "anon":"匿名地, 不久立刻地", 
    "ponder":"思考", 
    "conjecture":"猜想",
    "agitation":"搅动",
    "Nevertheless":"尽管如此, (表转折)",
    "garment":"costume",
    "tailor":"裁缝",
    "ungainliness":"un-gain-li-ness, n.怪样子, 丑陋",
    "fetish":"恋物癖",
    "relic":"遗迹",
    "meticulously":"精心的",
    "profound":"深刻的",
    "revelation":"启示录",
    "delicate":"精美的",
    "intrinsic":"固有的",
    "resolute":"坚决的",
    "adversity":"逆境",
    "ungainly":"笨拙地",
    "fastidious":"挑剔的, 考究的",
    "albatross":"信天翁",
    "boluse":"药丸",
    "engrossed":"全神贯注的",
    "styrofoam":"塑料泡沫",
    "permeat":"渗透",
    "artifact":"文物",
    "dissect":"解剖",
    "muck":"淤泥",
    "albeit":"甚至",
    "decipher":"破译",
    "mundane":"平凡的",
    "embark on a journey":"踏上旅途",
    "capsule":"胶囊",
    "flamboyant":"华丽的",
    "audacious":"大胆的, 鲁莽的",
    "captivating":"迷人的",
    "flaunt":"炫耀",
    "persona":"角色",
    "cerulean ":"天蓝色的",
    "radiant":"发光的",
    "descend":"下降",
    "dainty":"纤巧的",
    "molt":"蜕皮",
    "fledgling ":"雏鸟",
    "I began to molt into a new skin with fledgling wings.":"",
    "crusade ":"圣战, 运动",
    "merit":"优点",
    "jarring":"刺耳的",
    "epitomize":"概括",
    "transcend":"超越",
    "cognitive":"认知上的",
    "aversion":"厌恶",
    "caveat":"警告",
    "consense":"共识",
    "undermine":"破坏",
    "plausible":"合理的",
    "compelling":"引人注目的",
    "extrapolate":"推断",
    "preliminary":"初步的",
    "depict":"描绘",
    "bust":"半身像",
    "acquaintance":"熟人",
    "be faithful to ":"忠实于",
    "complement":"补充",
    "violent":"暴力的",
    "mundane":"平凡的",
    "intricate":"错综复杂的",
    "fleeting":"转瞬即逝的",
    "revered":"受人尊敬的",
    "obscure":"朦胧的",
    "precarious":"不稳定的, 岌岌可危的",
    "squander":"挥霍, 浪费",
    "approbation":"赞许",
    "discourse":"话语, 论述",
    "conform":"符合",
    "exaggerated":"夸大的, 夸张的",
    "recomend him to a yet higher notice":"向上级推荐他",
    "dimwitted":"笨的",
    "metropolis":"大城市",
    "render services":"提供服务",
    "rendered necessary by ...":"因...成为必要",
    "entrust to ...":"委托给...(某人)",
    "tact":"机智",
    "fondly":"怜爱地/盲目轻信地",
    "cooroborate":"证实",
    "confound":"使...惊讶/搅乱，混淆",
    "disseminate":"传播",
    "ameliorate":"改善",
    "impede":"阻碍",
    "maritime":"海上的",
    "endearing":"讨人喜欢的",
    "becoming acquanted with sb":"认识某人",
    "confiscate":"没收, 征用",
    "fasten":"紧固",
    "harrowing":"令人痛心",
    "gratify":"满足",
    "overlook":"忽略",
    "quarrel":"争吵",
    "remorse ":"悔恨",
    "vengeance ":"n. 复仇",
    "repulse ":"击退",
    "scorn":"蔑视",
    "Antecedent":"前因",
    "grief":"悲伤",
    "conceive":"设想",
    "allocate":"分配",
    "discernible":"可辨别的",
    "parasite":"寄生虫",
    "influx":"涌入",
    "spacial":"空间上的",
    "diffuse":"扩散",
    "feasible":"可行的, 可能的",
    "plausible":"合理的",
    "divulge":"泄露",
    "archbishop":"大主教",
    "capacious":"宽敞的",
    "dome":"圆顶",
    "confidence":"1. 自信  2:秘密 ",
    "disheveled":"衣冠不整的",
    "overshadow ..":"to be more important than...",
    "forfeiture of ...":"没收...",
    "compliance with ...":"遵守...",
    "subsumed in ...":"纳入...",
    "protagonist":"主角",
    "a grave person":"一个严肃的人",
    "savant":"学者",
    "coxcombical":"浮夸的",
    "ribbon ":"丝带",
    "lapel":"翻领",
    "furtive":"鬼鬼祟祟",
    "vigilance ":"警觉",
    "exacerbate":"加剧",
    "reimburse":"补偿, 退款",
    "That said":"尽管如此, 表转折",
    "Granted":"的确, admittedly",
    "diminish":"减少",
    "foreman":"领班",
    "juxtapose":"并置, 对比",
    "fortify":"强化",
    "apostrophe":"撇号, ' ",
    "clause":"条文",
    "subordinate":"下属",
    "preposition":"介词",
    "subject":"主体, 科目",
    "zesty":"热情洋溢的",
    "unanimous":"一致",
    "tenous":"脆弱的",
    "bribe":"贿赂",
    "trot":"小跑",
    "tindle":"叮当",
    "bladder":"膀胱",
    "mantra":"咒语",
    "perverse":"反常的",
    "realm":"领域",
    "delusion":"妄想",
    "carnivore":"食肉动物",
    "stipend":"津贴，助学金",
    "candid":"坦率的",
    "herd mentality":"从众心理",
    "vandalize":"故意破坏",
    "prevalent":"流行的",
    "rampant":"猖獗",
    "felonious":"有重罪的",
    "nuanced":"细致入微的",
    "wile":"诡计",
    "philantropy":"慈善事业",
    "penthouse":"顶层公寓",
    "buxom":"丰满的",
    "blotche":"斑点",
    "cleft lip":"唇裂",
    "ostracize":"排斥",
    "humanitarian":"人道主义",
    "assets":"资产",
    "rankled":"恼怒",
    "be keen about ...":"热衷于...",
    "launder":"洗钱",
    "jugggernaut":"巨型怪物",
    "remnant":"剩下的",
    "be consumed by ...":"对...着迷",
    "altruistic":"利他主义",
    "alleviate":"减轻",
    "stalk":"跟踪",
    "solicitate":"招揽",
    "colossal":"巨大的",
    "besseach":"恳求",
    "crooked":"歪的",
    "candor":"坦诚",
    "unilateral":"单方面的",
    "subtle":"微妙的",
    "entity":"实体",
    "nudge":"轻推",
    "subtle":"微妙的",
    "cue":"线索",
    "staunch":"坚定的",
    "stake":"赌注",
    "stalemate":"僵局",
    "coyly":"羞怯的",
    "rapture":"n. 狂喜",
    "bizarre":"奇怪的",
    "coddle":"溺爱",
    "endorser":"代言人",
    "intimate":"亲密的",
    "protracted":"旷日持久的",
    "quasi-..":"准...",
    

    



    



    

    

}

Grammer_lsit = { 
    1: "No puctuation between title and the person's name",
    2:"that of ...., ..., 'that of' referese to property of a noun",
    
}


Math = {

    '''
    % o Prism: 棱柱

    % o positive difference between the ranges of number:
            num_a = range_a_max - range_a_min
            num_b = range_b_max - range_b_min
            output = num_a - num_b

    %o value start at 100, 1 year later the value is 80
        the value DECREASED BY 20% of its value the preceding year

    %o b^2 -4ac >= 0, quadratic function have real solution

    %o by how many a person is expected to win -> total_he_got - total_opponent got

    %o check what the question is asking, every single word matters
    '''
}

